apiVersion: v1
kind: ConfigMap
metadata:
  name: sales-config
  namespace: sales
data:
  NODE_ENV: production
  PORT: "3000"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: flash_sales
  REDIS_HOST: redis
  REDIS_PORT: "6379"
